// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GOTOBALL_H
#define GOTOBALL_H

// PROJECT INCLUDES
#include "frc/commands/Subsystem.h"
#include "Robot.h"


class GoToBall: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	GoToBall();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;

private:
//  ENUMS
    enum GotoStateEnum {
		GotoStateUnknown = 0,
		GotoStateStartScan,
		GotoStateScanning,
		GotoStateReadData,
		GotoStateProcessData,
		GotoStateMoveArm,
		GotoStateGrabBall,
		GotoStateFinished,
		GototStateMax
	};

// VARIABLES
   GotoStateEnum  m_state = GotoStateUnknown;
   polarPoint     m_polarBallPt;
   int            m_cartX = 0; 
   int            m_cartY = 0;
   double         m_angle = 0.0;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};

#endif
