// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/GoToBall.h"



// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

GoToBall::GoToBall(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::manipulatorArm.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void GoToBall::Initialize() {
    // Reset the class variable for this iteration
    m_state = 0;

    m_polarBallPt.angle = 0.0;
    m_polarBallPt.dist  = 0;

    m_cartX = 0;
    m_cartY = 0;
    m_angle = 0.0;
    m_scanCnt = 0;
}

// Called repeatedly when this Command is scheduled to run
void GoToBall::Execute() {

    
    printf("\n");
}

// Make ifthis return true when this Command no longer needs to run execute()
bool GoToBall::IsFinished() {
    return (m_state == 8) ? true : false;    
}

// Called once after isFinished returns true
void GoToBall::End() {}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void GoToBall::Interrupted() {}
