// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/MoveArm.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

MoveArm::MoveArm(int btn): frc::Command() {
    m_btn = btn;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::manipulatorArm.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void MoveArm::Initialize() {
    done = false;
}

// Called repeatedly when this Command is scheduled to run
void MoveArm::Execute() {
    switch(m_btn) {
		case 0:
			break;
		case 1: //Carry
			done = Robot::manipulatorArm->moveTo(10);
			break;
		case 2: //Rocket Low
			done = Robot::manipulatorArm->moveTo(0);
			break;
		case 3: //Rocket Medium
			done = Robot::manipulatorArm->moveTo(1);
			break;
		case 4: //Rocket High
			done = Robot::manipulatorArm->moveTo(2);
			break;
		case 5: //Fine Motion
			
			break;
		case 6:	//Pick up
			
			break;
		case 7: //Human Station Hatch
			done = Robot::manipulatorArm->moveTo(3);
			break;
		case 8: //Human Station Cargo
			done = Robot::manipulatorArm->moveTo(6);
			break;
		case 9: //Swap Intake
			
			break;
		case 10: //Cargo Ship
			done = Robot::manipulatorArm->moveTo(7);
			break;
	}
}

// Make this return true when this Command no longer needs to run execute()
bool MoveArm::IsFinished() {
    return done;
}

// Called once after isFinished returns true
void MoveArm::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveArm::Interrupted() {

}
